variables:
  APP_NAME: "scriptcat-learn"
  REPOSITORY: "scriptcat/learn"

stages:
  - build
  - docker
  - deploy

build:
  stage: build
  image: node:16
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - npm ci
    - npm run build
  cache:
    key: node-cache
    paths:
      - node_modules
  artifacts:
    expire_in: 1 week
    paths:
      - build

build-docker:
  stage: docker
  image: docker:rc
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    DOCKER_HOST: tcp://docker-dind:2375
  before_script:
    - docker login $REGISTRY --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

  script:
    - docker build . -f deploy/docker/Dockerfile -t $REGISTRY/$REPOSITORY:$CI_COMMIT_SHORT_SHA
    - docker push $REGISTRY/$REPOSITORY:$CI_COMMIT_SHORT_SHA

deploy-job:
  stage: deploy
  image: alpine/helm:3.9.0
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - cd deploy/helm
    - helm upgrade --install --namespace app $APP_NAME . --kubeconfig $K3S_CONFIG --set image.tag=$CI_COMMIT_SHORT_SHA --set image.repository=$REGISTRY/$REPOSITORY
